/*
ADD_PRODUCT: que su valor sea 'ADD_PRODUCT'.
DELETE_PRODUCT: que su valor sea 'DELETE_PRODUCT'.
GET_STORE_NAME: que su valor sea 'GET_STORE_NAME'.
*/

const ADD_PRODUCT = 'ADD_PRODUCT'
const DELETE_PRODUCT = 'DELETE_PRODUCT'
const GET_STORE_NAME = 'GET_STORE_NAME'

export { ADD_PRODUCT, DELETE_PRODUCT, GET_STORE_NAME }